In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [3]:
df = pd.read_csv("dataset/diabates.csv")
df.head()

   Glucose   BMI  Age  Outcome
0      179  36.2   69        1
1      192  29.1   46        1
2      113  29.7   31        0
3      173  31.5   51        1
4      119  28.1   18        0

In [4]:
df.describe()

          Glucose         BMI         Age     Outcome
count  500.000000  500.000000  500.000000  500.000000
mean   121.692000   29.093800   40.254000    0.338000
std     31.576816    5.440432   11.791164    0.473502
min     70.000000   16.400000   18.000000    0.000000
25%     97.750000   25.175000   32.000000    0.000000
50%    114.000000   28.500000   40.000000    0.000000
75%    140.000000   32.600000   48.000000    1.000000
max    209.000000   48.100000   80.000000    1.000000

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Glucose  500 non-null    int64
 1   BMI      500 non-null    float64
 2   Age      500 non-null    int64
 3   Outcome  500 non-null    int64
dtypes: float64(1), int64(3)
memory usage: 15.8 KB

In [6]:
x = df.drop(columns = ['Outcome'])
y = df['Outcome']

In [7]:
x_train, x_test,y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [8]:
scalar = StandardScaler()
x_train = scalar.fit_transform(x_train)
x_test = scalar.fit_transform(x_test)

In [9]:
model = LogisticRegression()
model.fit(x_train, y_train)
pred = model.predict(x_test)

In [12]:
print(f"Accuracy Score: {accuracy_score(y_test, pred)}")

Accuracy Score: 0.92

In [14]:
print(f"Classification Report: {classification_report(y_test, pred)}")

Classification Report:               precision    recall  f1-score   support

           0       0.97      0.91      0.94        70
           1       0.82      0.93      0.88        30

    accuracy                           0.92       100
   macro avg       0.90      0.92      0.91       100
weighted avg       0.93      0.92      0.92       100

In [16]:
new_patient = [[140, 28.5, 45]]
new_patient_scaled = scalar.transform(new_patient)

new_pred = model.predict(new_patient_scaled)
if new_pred[0] == 1:
    print("Diabates")
else:
    print("Non Diabates")

Diabates

/home/riku/pyvn/lib/python3.12/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(